
package Util.WebServiceClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140803.1500
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookServiceImpl", targetNamespace = "http://WebService.Util/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBookDetailJson", targetNamespace = "http://WebService.Util/", className = "Util.WebServiceClient.GetBookDetailJson")
    @ResponseWrapper(localName = "getBookDetailJsonResponse", targetNamespace = "http://WebService.Util/", className = "Util.WebServiceClient.GetBookDetailJsonResponse")
    @Action(input = "http://WebService.Util/BookServiceImpl/getBookDetailJsonRequest", output = "http://WebService.Util/BookServiceImpl/getBookDetailJsonResponse")
    public String getBookDetailJson(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
